### ISSUE TITLE
Max, how to optimization objective function trace?

### ISSUE THREAD

**Issue by DragonCircle** [sods/paramz#26]
I'm using GPy, and I want to plot a figure like this, how to do this under paramz?
[https://ibb.co/k5fUWT](url)

**Comment by mzwiessele** [comment]
You will need to trace the objective and parameters manually. There is two ways of achieving this.
1. You inherit from the model you want to record and overwrite `parameters_changed` function. This function gets called once per iteration. In there you can record the parameters you want to record in an array of sorts. **Make sure you call the `super` `parameters_changed`!**
2. You write a little wrapper around the optimizer, which records the optimization process and then subsequently does the optimization. You will be exposed to the raw optimization array though, so you need to map back to the parameter names.

**Comment by DragonCircle** [comment]
Than you, Max! By the way, is there any framework like paramz that could do optimization such as ADMM and SGD? Because I want to implement RPCA, I don't known if paramz's Quasi Newton able to optimize RPCA's objective function

**Comment by mzwiessele** [comment]
You can use adadelta or rprop from the climin package in paramz :)

**Comment by DragonCircle** [comment]
Max, I have a question about optimization, I don't know if it's suitable to ask you here, but I really want to get some advice from an expert.

You implement Lasso regression using gradient based optimization algorithm, but I have been told that LASSO should be optimized using ADMM, because L1 regularizer is not differentiable. But actually LASSO can be optimized using gradient based algorithm, that is conflict in my knowledge. Why? What I'm missing? Is L1 regularizer actually differentiable or gradient descent or quasi-newton can optimize objective function with L1 regularizer event if it is not differentiable?
