### ISSUE TITLE
How can I use the scipy optimizer to optimize my model?

### ISSUE THREAD

**Issue by yenicelik** [sods/paramz#28]
I am trying to accomplish the following: Optimize the parameters of a numpy array using grid search.
For this, I want to avoid using the `model.optimize` method, but want to change the parameters of the model using a vector that has the same shape as the parameters vector.

Assume we have the following model (and that we have an evaluation function `get_loss`):

```
m = GPy.models.GPRegression(X, Y)

for coordinate_tuple in grid:
    m.assign_parameters(coordinate_tuple) # Where coordinate_tuple.shape == self.param_array.shape
    get_loss(m)
    ...
```

How can I modify the parameters vector? Can I simply re-assign to 
`m.parameters = coordinate_tuple` or does it require more operations?

**Comment by mzwiessele** [comment]
Yes!

m.param_array[:] = coordinate_tuple

Should do the trick!

**Comment by yenicelik** [comment]
Many thanks! I'll just write a quick test and then close the issue! :)
